# cloudbuild.yaml
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/docker-deploy/pv-bot:$SHORT_SHA"
      - "."
    env:
      - "DOCKER_BUILDKIT=1"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/docker-deploy/pv-bot:$SHORT_SHA"
    env:
      - "DOCKER_BUILDKIT=1"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud compute instances update-container ${_COMPUTE_INSTANCE_NAME} \
          --zone=us-central1-${_ZONE} \
          --container-image=us-central1-docker.pkg.dev/$PROJECT_ID/docker-deploy/pv-bot:$SHORT_SHA \
          --container-env "PV_DISCORD_BOT_PORT=${_PV_DISCORD_BOT_PORT},PV_DISCORD_TOKEN=$$PV_DISCORD_TOKEN,PV_API_URL=${_PV_API_URL},PV_GUILD_ID=${_PV_GUILD_ID}"
    secretEnv: ["PV_DISCORD_TOKEN"]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_NUMBER/secrets/bot-token/versions/latest"
      env: "PV_DISCORD_TOKEN"
