# cloudbuild.yaml
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/docker-deploy/pv-bot:$SHORT_SHA"
      - "."
    env:
      - "DOCKER_BUILDKIT=1"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/docker-deploy/pv-bot:$SHORT_SHA"
    env:
      - "DOCKER_BUILDKIT=1"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud compute instances update-container ${_COMPUTE_INSTANCE} \
          --zone=us-central1-c \
          --container-image=us-central1-docker.pkg.dev/$PROJECT_ID/docker-deploy/pv-bot:$SHORT_SHA \
          --container-env "PORT=${_PORT},DISCORD_TOKEN=$$DISCORD_TOKEN,API_HOST_ADDR=${_API_HOST_ADDR},PV_GUILD_ID=${_PV_GUILD_ID}"
    secretEnv: ["DISCORD_TOKEN"]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_NUMBER/secrets/bot-token/versions/latest"
      env: "DISCORD_TOKEN"
